---

- name: Install zsh with completion and syntax highlighting
  pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
  notify: change shell

- name: Install pure prompt for zsh
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: /home/{{ user.name }}/.zsh/pure
