---

- name: Install network tools
  pacman:
    name:
      - ethtool
      - wpa_supplicant
      - nmap
      - networkmanager
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - enable networkmanager
