---

- name: Install alsa-utils and pulseaudio tools
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
    state: present

- name: create directory for pulse
  file:
    path: "/home/{{ user.name }}/.config/pulse"
    state: directory
    owner: "{{ user.name }}"

- name: Deploy HiFi pulse audio daemon configuration
  template:
    src: daemon.conf.j2
    dest: "/home/{{ user.name }}/.config/pulse/daemon.conf"
  become_user: "{{ user.name }}"
  become: true
